
package my.example.generated_classes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentsPort", targetNamespace = "http://example.my/generated_classes")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentsPort {


    /**
     * 
     * @param getStudentRequest
     * @return
     *     returns my.example.generated_classes.GetStudentResponse
     */
    @WebMethod
    @WebResult(name = "getStudentResponse", targetNamespace = "http://example.my/generated_classes", partName = "getStudentResponse")
    public GetStudentResponse getStudent(
        @WebParam(name = "getStudentRequest", targetNamespace = "http://example.my/generated_classes", partName = "getStudentRequest")
        GetStudentRequest getStudentRequest);

}
